parameters:
#    cms_page.example.class: Cms\PageBundle\Example

services:
#    cms_page.example:
#        class: %cms_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
